[workspace]
members = [
    "branches",
    "calculator",
    "cwc",
    "enums",
    "functions",
    "guessing_game",
    "hello_cargo",
    "loops",
    "ownership",
    "rectangles",
    "restaurant",
    "structs",
    "types",
    "variables",
]